package erebus.registries.entity;

import erebus.Erebus;
import erebus.client.render.entity.model.*;
import erebus.client.render.entity.model.layer.*;
import erebus.client.render.entity.renderer.*;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.renderer.entity.ThrownItemRenderer;
import net.neoforged.neoforge.client.event.EntityRenderersEvent;

public class ModEntityRendering {

    public static ModelLayerLocation ANIMATED_BLOCK = register("animated_block");
	public static ModelLayerLocation ANTLION = register("antlion");
	public static ModelLayerLocation ANTLION_BOSS = register("antlion_boss");
	public static ModelLayerLocation ANTLION_MINI_BOSS = register("antlion_mini_boss");
	public static ModelLayerLocation ANT = register("ant");
	public static ModelLayerLocation BED_BUG = register("bed_bug");
	public static ModelLayerLocation BEETLE = register("beetle");
	public static ModelLayerLocation BEETLE_LARVA = register("beetle_larva");
	public static ModelLayerLocation BLACK_ANT = register("black_ant");
	public static ModelLayerLocation BLACK_ANT_COLLECTOR = registerLayer("black_ant", "collector");
	public static ModelLayerLocation BLACK_ANT_FERTILIZER = registerLayer("black_ant", "fertilizer");
	public static ModelLayerLocation BLACK_ANT_HARVESTER = registerLayer("black_ant", "harvester");
	public static ModelLayerLocation BLACK_ANT_PLANTER = registerLayer("black_ant", "planter");
	public static ModelLayerLocation BLACK_WIDOW = register("black_widow");
	public static ModelLayerLocation BLOOD_SNAIL = register("blood_snail");
	public static ModelLayerLocation BOG_MAW = register("bog_maw");
	public static ModelLayerLocation BOMBARDIER_BEETLE = register("bombardier_beetle");
	public static ModelLayerLocation BOMBARDIER_BEETLE_LARVA = register("bombardier_beetle_larva");
	public static ModelLayerLocation BOT_FLY = register("bot_fly");
	public static ModelLayerLocation BOT_FLY_LARVA = register("bot_fly_larva");
	public static ModelLayerLocation CENTIPEDE = register("centipede");
	public static ModelLayerLocation CHAMELEON_TICK = register("chameleon_tick");
	public static ModelLayerLocation CICADA = register("cicada");
	public static ModelLayerLocation CRUSHROOM = register("crushroom");
	public static ModelLayerLocation CROP_WEEVIL = register("crop_weevil");
	public static ModelLayerLocation DRAGON_FLY = register("dragon_fly");
	public static ModelLayerLocation FIRE_ANT = register("fire_ant");
	public static ModelLayerLocation FIRE_ANT_SOLDIER = register("fire_ant_soldier");
	public static ModelLayerLocation FLY = register("fly");
	public static ModelLayerLocation FUNGAL_WEEVIL = register("fungal_weevil");
	public static ModelLayerLocation GLOW_WORM = register("glow_worm");
	public static ModelLayerLocation GRASSHOPPER = register("grasshopper");
	public static ModelLayerLocation HONEY_POT_ANT = register("honey_pot_ant");
	public static ModelLayerLocation JUMPING_SPIDER = register("jumping_spider");
	public static ModelLayerLocation LAVA_WEB_SPIDER = register("lava_web_spider");
	public static ModelLayerLocation LAVA_WEB_SPIDER_FLOW = register("lava_web_spider_flow");
	public static ModelLayerLocation LEECH = register("leech");
	public static ModelLayerLocation LOCUST = register("locust");
	public static ModelLayerLocation MAGMA_CRAWLER = register("magma_crawler");
	public static ModelLayerLocation MIDGE_SWARM = register("midge_swarm");
	public static ModelLayerLocation MONEY_SPIDER = register("money_spider");
	public static ModelLayerLocation MOSQUITO = register("mosquito");
	public static ModelLayerLocation MOTH = register("moth");
	public static ModelLayerLocation POND_SKATER = register("pond_skater");
	public static ModelLayerLocation PRAYING_MANTIS = register("praying_mantis");
	public static ModelLayerLocation PUNCHROOM = register("punchroom");
	public static ModelLayerLocation RHINO_BEETLE = register("rhino_beetle");
	public static ModelLayerLocation SCORPION = register("scorpion");
	public static ModelLayerLocation SCYTODES = register("scytodes");
	public static ModelLayerLocation SOLDIER_ANT = register("soldier_ant");
	public static ModelLayerLocation SOLIFUGE = register("solifuge");
	public static ModelLayerLocation TARANTULA = register("tarantula");
	public static ModelLayerLocation TARANTULA_MINI_BOSS = register("tarantula_mini_boss");
	public static ModelLayerLocation TARANTULA_BABY = register("tarantula_baby");
	public static ModelLayerLocation TITAN_BEETLE = register("titan_beetle");
	public static ModelLayerLocation UMBER_GOLEM = register("umber_golem");
	public static ModelLayerLocation VELVET_WORM = register("velvet_worm");
	public static ModelLayerLocation WASP = register("wasp");
	public static ModelLayerLocation WASP_WINGS = registerLayer("wasp", "wings");
	public static ModelLayerLocation WOODLOUSE = register("woodlouse");
	public static ModelLayerLocation WORKER_BEE = register("worker_bee");
	public static ModelLayerLocation ZOMBIE_ANT = register("zombie_ant");
	public static ModelLayerLocation ZOMBIE_ANT_SOLDIER = register("zombie_ant_soldier");

	private static ModelLayerLocation register(String name) {
		return new ModelLayerLocation(Erebus.prefix(name), "main");
	}

	private static ModelLayerLocation registerLayer(String name, String layer) {
		return new ModelLayerLocation(Erebus.prefix(name), layer);
	}

    public static void registerEntityLayers(EntityRenderersEvent.RegisterLayerDefinitions event) {
		event.registerLayerDefinition(ANIMATED_BLOCK, AnimatedBlockModel::createBodyLayer);
		event.registerLayerDefinition(ANTLION, AntlionModel::createBodyLayer);
		event.registerLayerDefinition(ANTLION_BOSS, AntlionBossModel::createBodyLayer);
		event.registerLayerDefinition(ANTLION_MINI_BOSS, AntlionMiniBossModel::createBodyLayer);
		event.registerLayerDefinition(ANT, AntModel::createBodyLayer);
		event.registerLayerDefinition(BED_BUG, BedBugModel::createBodyLayer);
		event.registerLayerDefinition(BEETLE, BeetleModel::createBodyLayer);
		event.registerLayerDefinition(BEETLE_LARVA, BeetleLarvaModel::createBodyLayer);
		event.registerLayerDefinition(BLACK_ANT, BlackAntModel::createBodyLayer);
		event.registerLayerDefinition(BLACK_ANT_COLLECTOR, BlackAntCollectorModel::createBodyLayer);
		event.registerLayerDefinition(BLACK_ANT_FERTILIZER, BlackAntFertilizerModel::createBodyLayer);
		event.registerLayerDefinition(BLACK_ANT_HARVESTER, BlackAntHarvesterModel::createBodyLayer);
		event.registerLayerDefinition(BLACK_ANT_PLANTER, BlackAntPlanterModel::createBodyLayer);
		event.registerLayerDefinition(BLACK_WIDOW, BlackWidowModel::createBodyLayer);
		event.registerLayerDefinition(BLOOD_SNAIL, BloodSnailModel::createBodyLayer);
		event.registerLayerDefinition(BOG_MAW, BogMawModel::createBodyLayer);
		event.registerLayerDefinition(BOMBARDIER_BEETLE, BombardierBeetleModel::createBodyLayer);
		event.registerLayerDefinition(BOMBARDIER_BEETLE_LARVA, BeetleLarvaModel::createBodyLayer);
		event.registerLayerDefinition(BOT_FLY, BotFlyModel::createBodyLayer);
		event.registerLayerDefinition(BOT_FLY_LARVA, BotFlyLarvaModel::createBodyLayer);
		event.registerLayerDefinition(CENTIPEDE, CentipedeModel::createBodyLayer);
		event.registerLayerDefinition(CHAMELEON_TICK, ChameleonTickModel::createBodyLayer);
		event.registerLayerDefinition(CICADA, CicadaModel::createBodyLayer);
		event.registerLayerDefinition(CRUSHROOM, CrushroomModel::createBodyLayer);
		event.registerLayerDefinition(CROP_WEEVIL, WeevilModel::createBodyLayer);
		event.registerLayerDefinition(DRAGON_FLY, DragonflyModel::createBodyLayer);
		event.registerLayerDefinition(FIRE_ANT, FireAntModel::createBodyLayer);
		event.registerLayerDefinition(FIRE_ANT_SOLDIER, SoldierAntModel::createBodyLayer);
		event.registerLayerDefinition(FLY, FlyModel::createBodyLayer);
		event.registerLayerDefinition(FUNGAL_WEEVIL, WeevilModel::createBodyLayer);
		event.registerLayerDefinition(GLOW_WORM, GlowWormModel::createBodyLayer);
		event.registerLayerDefinition(GRASSHOPPER, GrasshopperModel::createBodyLayer);
		event.registerLayerDefinition(HONEY_POT_ANT, HoneyPotAntModel::createBodyLayer);
		event.registerLayerDefinition(JUMPING_SPIDER, JumpingSpiderModel::createBodyLayer);
		event.registerLayerDefinition(LAVA_WEB_SPIDER, LavaWebSpiderModel::createBodyLayer);
		event.registerLayerDefinition(LAVA_WEB_SPIDER_FLOW, LavaWebSpiderModel::createBodyLayer);
		event.registerLayerDefinition(LEECH, LeechModel::createBodyLayer);
		event.registerLayerDefinition(LOCUST, LocustModel::createBodyLayer);
		event.registerLayerDefinition(MAGMA_CRAWLER, MagmaCrawlerModel::createBodyLayer);
		event.registerLayerDefinition(MIDGE_SWARM, FlyModel::createBodyLayer);
		event.registerLayerDefinition(MONEY_SPIDER, ScytodesModel::createBodyLayer);
		event.registerLayerDefinition(MOSQUITO, MosquitoModel::createBodyLayer);
		event.registerLayerDefinition(MOTH, MothModel::createBodyLayer);
		event.registerLayerDefinition(POND_SKATER, PondSkaterModel::createBodyLayer);
		event.registerLayerDefinition(PRAYING_MANTIS, PrayingMantisModel::createBodyLayer);
		event.registerLayerDefinition(PUNCHROOM, PunchroomModel::createBodyLayer);
		event.registerLayerDefinition(RHINO_BEETLE, RhinoBeetleModel::createBodyLayer);
		event.registerLayerDefinition(SCORPION, ScorpionModel::createBodyLayer);
		event.registerLayerDefinition(SCYTODES, ScytodesModel::createBodyLayer);
		event.registerLayerDefinition(SOLDIER_ANT, SoldierAntModel::createBodyLayer);
		event.registerLayerDefinition(SOLIFUGE, SolifugeModel::createBodyLayer);
		event.registerLayerDefinition(TARANTULA, TarantulaModel::createBodyLayer);
		event.registerLayerDefinition(TARANTULA_MINI_BOSS, TarantulaMiniBossModel::createBodyLayer);
		event.registerLayerDefinition(TARANTULA_BABY, TarantulaBabyModel::createBodyLayer);
		event.registerLayerDefinition(TITAN_BEETLE, TitanBeetleModel::createBodyLayer);
		event.registerLayerDefinition(UMBER_GOLEM, UmberGolemModel::createBodyLayer);
		event.registerLayerDefinition(VELVET_WORM, VelvetWormModel::createBodyLayer);
		event.registerLayerDefinition(WASP, WaspModel::createBodyLayer);
		event.registerLayerDefinition(WASP_WINGS, WaspWingsModel::createBodyLayer);
		event.registerLayerDefinition(WOODLOUSE, WoodlouseModel::createBodyLayer);
		event.registerLayerDefinition(WORKER_BEE, WorkerBeeModel::createBodyLayer);
		event.registerLayerDefinition(ZOMBIE_ANT, AntModel::createBodyLayer);
		event.registerLayerDefinition(ZOMBIE_ANT_SOLDIER, SoldierAntModel::createBodyLayer);
	}

    public static void registerEntityRender(EntityRenderersEvent.RegisterRenderers event) {
		event.registerEntityRenderer(ModEntities.ANIMATED_BLOCK.get(), AnimatedBlockRenderer::new);
		event.registerEntityRenderer(ModEntities.ANTLION.get(), AntlionRenderer::new);
		event.registerEntityRenderer(ModEntities.ANTLION_BOSS.get(), AntlionBossRenderer::new);
		event.registerEntityRenderer(ModEntities.ANTLION_MINI_BOSS.get(), AntlionMiniBossRenderer::new);
		event.registerEntityRenderer(ModEntities.BED_BUG.get(), BedBugRenderer::new);
		event.registerEntityRenderer(ModEntities.BABY_SOLIFUGE.get(), BabySolifugeRenderer::new);
		event.registerEntityRenderer(ModEntities.BABY_TARANTULA.get(), BabyTarantulaRenderer::new);
		event.registerEntityRenderer(ModEntities.BEETLE.get(), BeetleRenderer::new);
		event.registerEntityRenderer(ModEntities.BEETLE_LARVA.get(), BeetleLarvaRenderer::new);
		event.registerEntityRenderer(ModEntities.BLACK_ANT.get(), BlackAntRenderer::new);
		event.registerEntityRenderer(ModEntities.BLACK_WIDOW.get(), BlackWidowRenderer::new);
		event.registerEntityRenderer(ModEntities.BOG_MAW.get(), BogMawRenderer::new);
		event.registerEntityRenderer(ModEntities.BOMBARDIER_BEETLE.get(), BombardierBeetleRenderer::new);
		event.registerEntityRenderer(ModEntities.BOMBARDIER_BEETLE_LARVA.get(), BeetleLarvaRenderer::new);
		event.registerEntityRenderer(ModEntities.BOT_FLY.get(), BotFlyRenderer::new);
		event.registerEntityRenderer(ModEntities.BOT_FLY_LARVA.get(), BotFlyLarvaRenderer::new);
		event.registerEntityRenderer(ModEntities.CENTIPEDE.get(), CentipedeRenderer::new);
		event.registerEntityRenderer(ModEntities.CHAMELEON_TICK.get(), ChameleonTickRenderer::new);
		event.registerEntityRenderer(ModEntities.CICADA.get(), CicadaRenderer::new);
		event.registerEntityRenderer(ModEntities.CROP_WEEVIL.get(), CropWeevilRenderer::new);
		event.registerEntityRenderer(ModEntities.CRUSHROOM.get(), CrushroomRenderer::new);
		event.registerEntityRenderer(ModEntities.DRAGON_FLY.get(), DragonflyRenderer::new);
		event.registerEntityRenderer(ModEntities.FLY.get(), FlyRenderer::new);
		event.registerEntityRenderer(ModEntities.FUNGAL_WEEVIL.get(), FungalWeevilRenderer::new);
		event.registerEntityRenderer(ModEntities.GLOW_WORM.get(), GlowWormRenderer::new);
		event.registerEntityRenderer(ModEntities.GRASSHOPPER.get(), GrasshopperRenderer::new);
		event.registerEntityRenderer(ModEntities.HONEY_POT_ANT.get(), HoneyPotAntRenderer::new);
		event.registerEntityRenderer(ModEntities.JUMPING_SPIDER.get(), JumpingSpiderRenderer::new);
		event.registerEntityRenderer(ModEntities.LAVA_WEB_SPIDER.get(), LavaWebSpiderRenderer::new);
		event.registerEntityRenderer(ModEntities.LOCUST.get(), LocustRenderer::new);
		event.registerEntityRenderer(ModEntities.MAGMA_CRAWLER.get(), MagmaCrawlerRenderer::new);
		event.registerEntityRenderer(ModEntities.MIDGE_SWARM.get(), MidgeSwarmRenderer::new);
		event.registerEntityRenderer(ModEntities.MONEY_SPIDER.get(), MoneySpiderRenderer::new);
		event.registerEntityRenderer(ModEntities.MOSQUITO.get(), MosquitoRenderer::new);
		event.registerEntityRenderer(ModEntities.MOTH.get(), MothRenderer::new);
		event.registerEntityRenderer(ModEntities.POND_SKATER.get(), PondSkaterRenderer::new);
		event.registerEntityRenderer(ModEntities.PRAYING_MANTIS.get(), PrayingMantisRenderer::new);
		event.registerEntityRenderer(ModEntities.PUNCHROOM.get(), PunchroomRenderer::new);
		event.registerEntityRenderer(ModEntities.RHINO_BEETLE.get(), RhinoBeetleRenderer::new);
		event.registerEntityRenderer(ModEntities.SCORPION.get(), ScorpionRenderer::new);
		event.registerEntityRenderer(ModEntities.SCYTODES.get(), ScytodesRenderer::new);
		event.registerEntityRenderer(ModEntities.SOLIFUGE.get(), SolifugeRenderer::new);
		event.registerEntityRenderer(ModEntities.STAG_BEETLE.get(), StagBeetleRenderer::new);
		event.registerEntityRenderer(ModEntities.TARANTULA.get(), TarantulaRenderer::new);
		event.registerEntityRenderer(ModEntities.TARANTULA_MINI_BOSS.get(), TarantulaMiniBossRenderer::new);
		event.registerEntityRenderer(ModEntities.TITAN_BEETLE.get(), TitanBeetleRenderer::new);
		event.registerEntityRenderer(ModEntities.UMBER_GOLEM.get(), UmberGolemRenderer::new);
		event.registerEntityRenderer(ModEntities.VELVET_WORM.get(), VelvetWormRenderer::new);
		event.registerEntityRenderer(ModEntities.WASP.get(), WaspRenderer::new);
		event.registerEntityRenderer(ModEntities.WOODLOUSE.get(), WoodlouseRenderer::new);
		event.registerEntityRenderer(ModEntities.WORKER_BEE.get(), WorkerBeeRenderer::new);
		event.registerEntityRenderer(ModEntities.ZOMBIE_ANT.get(), ZombieAntRenderer::new);
		event.registerEntityRenderer(ModEntities.ZOMBIE_ANT_SOLDIER.get(), ZombieAntSoldierRenderer::new);

		event.registerEntityRenderer(ModEntities.AMBER_STAR.get(), context -> new ThrownItemRenderer<>(context, 3.0F, true));
		event.registerEntityRenderer(ModEntities.GOO_BALL.get(), context -> new ThrownItemRenderer<>(context, 3.0F, true));
		event.registerEntityRenderer(ModEntities.THROWN_BLOCK_AS_ITEM.get(), context -> new ThrownItemRenderer<>(context, 3.0F, true));
	}
}
