package erebus.registries.entity;

import erebus.Erebus;
import erebus.entity.*;
import erebus.entity.projectile.AmberStar;
import erebus.entity.projectile.GooBall;
import erebus.entity.projectile.ThrownBlockAsItem;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.MobCategory;
import net.minecraft.world.level.Level;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

public class ModEntities {

    public static DeferredRegister<EntityType<?>> ENTITY_TYPES;

	public static final ResourceKey<EntityType<?>> AMBER_STAR_KEY;
	public static final ResourceKey<EntityType<?>> ANIMATED_BLOCK_KEY;
	public static final ResourceKey<EntityType<?>> ANTLION_KEY;
	public static final ResourceKey<EntityType<?>> ANTLION_BOSS_KEY;
	public static final ResourceKey<EntityType<?>> ANTLION_MINI_BOSS_KEY;
	public static final ResourceKey<EntityType<?>> BABY_SOLIFUGE_KEY;
	public static final ResourceKey<EntityType<?>> BABY_TARANTULA_KEY;
	public static final ResourceKey<EntityType<?>> BED_BUG_KEY;
	public static final ResourceKey<EntityType<?>> BEETLE_KEY;
	public static final ResourceKey<EntityType<?>> BEETLE_LARVA_KEY;
	public static final ResourceKey<EntityType<?>> BLACK_ANT_KEY;
	public static final ResourceKey<EntityType<?>> BLACK_WIDOW_KEY;
	public static final ResourceKey<EntityType<?>> BOG_MAW_KEY;
	public static final ResourceKey<EntityType<?>> BOMBARDIER_BEETLE_KEY;
	public static final ResourceKey<EntityType<?>> BOMBARDIER_BEETLE_LARVA_KEY;
	public static final ResourceKey<EntityType<?>> BOT_FLY_KEY;
	public static final ResourceKey<EntityType<?>> BOT_FLY_LARVA_KEY;
	public static final ResourceKey<EntityType<?>> CENTIPEDE_KEY;
	public static final ResourceKey<EntityType<?>> CHAMELEON_TICK_KEY;
	public static final ResourceKey<EntityType<?>> CICADA_KEY;
	public static final ResourceKey<EntityType<?>> CROP_WEEVIL_KEY;
	public static final ResourceKey<EntityType<?>> CRUSHROOM_KEY;
	public static final ResourceKey<EntityType<?>> DRAGON_FLY_KEY;
	public static final ResourceKey<EntityType<?>> FIRE_ANT_KEY;
	public static final ResourceKey<EntityType<?>> FIRE_ANT_SOLDIER_KEY;
	public static final ResourceKey<EntityType<?>> FLY_KEY;
	public static final ResourceKey<EntityType<?>> FUNGAL_WEEVIL_KEY;
	public static final ResourceKey<EntityType<?>> GOO_BALL_KEY;
	public static final ResourceKey<EntityType<?>> GLOW_WORM_KEY;
	public static final ResourceKey<EntityType<?>> GRASSHOPPER_KEY;
	public static final ResourceKey<EntityType<?>> HONEY_POT_ANT_KEY;
	public static final ResourceKey<EntityType<?>> JUMPING_SPIDER_KEY;
	public static final ResourceKey<EntityType<?>> LAVA_WEB_SPIDER_KEY;
	public static final ResourceKey<EntityType<?>> LOCUST_KEY;
	public static final ResourceKey<EntityType<?>> MAGMA_CRAWLER_KEY;
	public static final ResourceKey<EntityType<?>> MIDGE_SWARM_KEY;
	public static final ResourceKey<EntityType<?>> MONEY_SPIDER_KEY;
	public static final ResourceKey<EntityType<?>> MOSQUITO_KEY;
	public static final ResourceKey<EntityType<?>> MOTH_KEY;
	public static final ResourceKey<EntityType<?>> POND_SKATER_KEY;
	public static final ResourceKey<EntityType<?>> PRAYING_MANTIS_KEY;
	public static final ResourceKey<EntityType<?>> PUNCHROOM_KEY;
	public static final ResourceKey<EntityType<?>> RHINO_BEETLE_KEY;
	public static final ResourceKey<EntityType<?>> SCORPION_KEY;
	public static final ResourceKey<EntityType<?>> SCYTODES_KEY;
	public static final ResourceKey<EntityType<?>> SOLIFUGE_KEY;
	public static final ResourceKey<EntityType<?>> STAG_BEETLE_KEY;
	public static final ResourceKey<EntityType<?>> TARANTULA_KEY;
	public static final ResourceKey<EntityType<?>> TARANTULA_MINI_BOSS_KEY;
	public static final ResourceKey<EntityType<?>> THROWN_BLOCK_AS_ITEM_KEY;
	public static final ResourceKey<EntityType<?>> TITAN_BEETLE_KEY;
	public static final ResourceKey<EntityType<?>> UMBER_GOLEM_KEY;
	public static final ResourceKey<EntityType<?>> VELVET_WORM_KEY;
	public static final ResourceKey<EntityType<?>> WASP_KEY;
	public static final ResourceKey<EntityType<?>> WOODLOUSE_KEY;
	public static final ResourceKey<EntityType<?>> WORKER_BEE_KEY;
	public static final ResourceKey<EntityType<?>> ZOMBIE_ANT_KEY;
	public static final ResourceKey<EntityType<?>> ZOMBIE_ANT_SOLDIER_KEY;

    public static final DeferredHolder<EntityType<?>, EntityType<AmberStar>> AMBER_STAR;
    public static final DeferredHolder<EntityType<?>, EntityType<AnimatedBlock>> ANIMATED_BLOCK;
    public static final DeferredHolder<EntityType<?>, EntityType<Antlion>> ANTLION;
	public static final DeferredHolder<EntityType<?>, EntityType<AntlionBoss>> ANTLION_BOSS;
	public static final DeferredHolder<EntityType<?>, EntityType<AntlionMiniBoss>> ANTLION_MINI_BOSS;
	public static final DeferredHolder<EntityType<?>, EntityType<BabySolifuge>> BABY_SOLIFUGE;
	public static final DeferredHolder<EntityType<?>, EntityType<BabyTarantula>> BABY_TARANTULA;
    public static final DeferredHolder<EntityType<?>, EntityType<BedBug>> BED_BUG;
    public static final DeferredHolder<EntityType<?>, EntityType<Beetle>> BEETLE;
    public static final DeferredHolder<EntityType<?>, EntityType<BeetleLarva>> BEETLE_LARVA;
    public static final DeferredHolder<EntityType<?>, EntityType<BlackAnt>> BLACK_ANT;
    public static final DeferredHolder<EntityType<?>, EntityType<BlackWidow>> BLACK_WIDOW;
	public static final DeferredHolder<EntityType<?>, EntityType<BogMaw>> BOG_MAW;
    public static final DeferredHolder<EntityType<?>, EntityType<BombardierBeetle>> BOMBARDIER_BEETLE;
    public static final DeferredHolder<EntityType<?>, EntityType<BombardierBeetleLarva>> BOMBARDIER_BEETLE_LARVA;
    public static final DeferredHolder<EntityType<?>, EntityType<BotFly>> BOT_FLY;
    public static final DeferredHolder<EntityType<?>, EntityType<BotFlyLarva>> BOT_FLY_LARVA;
    public static final DeferredHolder<EntityType<?>, EntityType<Centipede>> CENTIPEDE;
    public static final DeferredHolder<EntityType<?>, EntityType<ChameleonTick>> CHAMELEON_TICK;
	public static final DeferredHolder<EntityType<?>, EntityType<Cicada>> CICADA;
    public static final DeferredHolder<EntityType<?>, EntityType<CropWeevil>> CROP_WEEVIL;
    public static final DeferredHolder<EntityType<?>, EntityType<Crushroom>> CRUSHROOM;
    public static final DeferredHolder<EntityType<?>, EntityType<Dragonfly>> DRAGON_FLY;
    public static final DeferredHolder<EntityType<?>, EntityType<FireAnt>> FIRE_ANT;
    public static final DeferredHolder<EntityType<?>, EntityType<FireAntSoldier>> FIRE_ANT_SOLDIER;
    public static final DeferredHolder<EntityType<?>, EntityType<Fly>> FLY;
    public static final DeferredHolder<EntityType<?>, EntityType<FungalWeevil>> FUNGAL_WEEVIL;
    public static final DeferredHolder<EntityType<?>, EntityType<GooBall>> GOO_BALL;
	public static final DeferredHolder<EntityType<?>, EntityType<GlowWorm>> GLOW_WORM;
    public static final DeferredHolder<EntityType<?>, EntityType<Grasshopper>> GRASSHOPPER;
    public static final DeferredHolder<EntityType<?>, EntityType<HoneyPotAnt>> HONEY_POT_ANT;
	public static final DeferredHolder<EntityType<?>, EntityType<JumpingSpider>> JUMPING_SPIDER;
    public static final DeferredHolder<EntityType<?>, EntityType<LavaWebSpider>> LAVA_WEB_SPIDER;
    public static final DeferredHolder<EntityType<?>, EntityType<Locust>> LOCUST;
    public static final DeferredHolder<EntityType<?>, EntityType<MagmaCrawler>> MAGMA_CRAWLER;
    public static final DeferredHolder<EntityType<?>, EntityType<MidgeSwarm>> MIDGE_SWARM;
    public static final DeferredHolder<EntityType<?>, EntityType<MoneySpider>> MONEY_SPIDER;
    public static final DeferredHolder<EntityType<?>, EntityType<Mosquito>> MOSQUITO;
    public static final DeferredHolder<EntityType<?>, EntityType<Moth>> MOTH;
	public static final DeferredHolder<EntityType<?>, EntityType<PondSkater>> POND_SKATER;
	public static final DeferredHolder<EntityType<?>, EntityType<PrayingMantis>> PRAYING_MANTIS;
    public static final DeferredHolder<EntityType<?>, EntityType<Punchroom>> PUNCHROOM;
	public static final DeferredHolder<EntityType<?>, EntityType<RhinoBeetle>> RHINO_BEETLE;
	public static final DeferredHolder<EntityType<?>, EntityType<Scorpion>> SCORPION;
    public static final DeferredHolder<EntityType<?>, EntityType<Scytodes>> SCYTODES;
    public static final DeferredHolder<EntityType<?>, EntityType<Solifuge>> SOLIFUGE;
	public static final DeferredHolder<EntityType<?>, EntityType<StagBeetle>> STAG_BEETLE;
    public static final DeferredHolder<EntityType<?>, EntityType<Tarantula>> TARANTULA;
    public static final DeferredHolder<EntityType<?>, EntityType<TarantulaMiniBoss>> TARANTULA_MINI_BOSS;
    public static final DeferredHolder<EntityType<?>, EntityType<ThrownBlockAsItem>> THROWN_BLOCK_AS_ITEM;
	public static final DeferredHolder<EntityType<?>, EntityType<TitanBeetle>> TITAN_BEETLE;
	public static final DeferredHolder<EntityType<?>, EntityType<UmberGolem>> UMBER_GOLEM;
    public static final DeferredHolder<EntityType<?>, EntityType<VelvetWorm>> VELVET_WORM;
    public static final DeferredHolder<EntityType<?>, EntityType<Wasp>> WASP;
	public static final DeferredHolder<EntityType<?>, EntityType<Woodlouse>> WOODLOUSE;
    public static final DeferredHolder<EntityType<?>, EntityType<WorkerBee>> WORKER_BEE;
    public static final DeferredHolder<EntityType<?>, EntityType<ZombieAnt>> ZOMBIE_ANT;
    public static final DeferredHolder<EntityType<?>, EntityType<ZombieAntSoldier>> ZOMBIE_ANT_SOLDIER;

	static {
		ENTITY_TYPES = DeferredRegister.create(BuiltInRegistries.ENTITY_TYPE, Erebus.MODID);

		AMBER_STAR_KEY = createKey("amber_star");
		ANIMATED_BLOCK_KEY = createKey("animated_block");
		ANTLION_KEY = createKey("antlion");
		ANTLION_BOSS_KEY = createKey("antlion_boss");
		ANTLION_MINI_BOSS_KEY = createKey("antlion_mini_boss");
		BABY_SOLIFUGE_KEY = createKey("baby_solifuge");
		BABY_TARANTULA_KEY = createKey("baby_tarantula");
		BED_BUG_KEY = createKey("bed_bug");
		BEETLE_KEY = createKey("beetle");
		BEETLE_LARVA_KEY = createKey("beetle_larva");
		BLACK_ANT_KEY = createKey("black_ant");
		BLACK_WIDOW_KEY = createKey("black_widow");
		BOG_MAW_KEY = createKey("bog_maw");
		BOMBARDIER_BEETLE_KEY = createKey("bombardier_beetle");
		BOMBARDIER_BEETLE_LARVA_KEY = createKey("bombardier_beetle_larva");
		BOT_FLY_KEY = createKey("bot_fly");
		BOT_FLY_LARVA_KEY = createKey("bot_fly_larva");
		CENTIPEDE_KEY = createKey("centipede");
		CHAMELEON_TICK_KEY = createKey("chameleon_tick");
		CICADA_KEY = createKey("cicada");
		CROP_WEEVIL_KEY = createKey("crop_weevil");
		CRUSHROOM_KEY = createKey("crushroom");
		DRAGON_FLY_KEY = createKey("dragon_fly");
		FIRE_ANT_KEY = createKey("fire_ant");
		FIRE_ANT_SOLDIER_KEY = createKey("fire_ant_soldier");
		FLY_KEY = createKey("fly");
		FUNGAL_WEEVIL_KEY = createKey("fungal_weevil");
		GOO_BALL_KEY = createKey("goo_ball");
		GLOW_WORM_KEY = createKey("glow_worm");
		GRASSHOPPER_KEY = createKey("grasshopper");
		HONEY_POT_ANT_KEY = createKey("honey_pot_ant");
		JUMPING_SPIDER_KEY = createKey("jumping_spider");
		LAVA_WEB_SPIDER_KEY = createKey("lava_web_spider");
		LOCUST_KEY = createKey("locust");
		MAGMA_CRAWLER_KEY = createKey("magma_crawler");
		MIDGE_SWARM_KEY = createKey("midge_swarm");
		MONEY_SPIDER_KEY = createKey("money_spider");
		MOSQUITO_KEY = createKey("mosquito");
		MOTH_KEY = createKey("moth");
		POND_SKATER_KEY = createKey("pond_skater");
		PRAYING_MANTIS_KEY = createKey("praying_mantis");
		PUNCHROOM_KEY = createKey("punchroom");
		RHINO_BEETLE_KEY = createKey("rhino_beetle");
		SCORPION_KEY = createKey("scorpion");
		SCYTODES_KEY = createKey("scytodes");
		SOLIFUGE_KEY = createKey("solifuge");
		STAG_BEETLE_KEY = createKey("stag_beetle");
		TARANTULA_KEY = createKey("tarantula");
		TARANTULA_MINI_BOSS_KEY = createKey("tarantula_mini_boss");
		THROWN_BLOCK_AS_ITEM_KEY = createKey("thrown_block_as_item");
		TITAN_BEETLE_KEY = createKey("titan_beetle");
		UMBER_GOLEM_KEY = createKey("umber_golem");
		VELVET_WORM_KEY = createKey("velvet_worm");
		WASP_KEY = createKey("wasp");
		WOODLOUSE_KEY = createKey("woodlouse");
		WORKER_BEE_KEY = createKey("worker_bee");
		ZOMBIE_ANT_KEY = createKey("zombie_ant");
		ZOMBIE_ANT_SOLDIER_KEY = createKey("zombie_ant_soldier");

		AMBER_STAR = register("amber_star", EntityType.Builder.<AmberStar>of(AmberStar::new, MobCategory.MISC).fireImmune().sized(0.5F, 0.5F), AMBER_STAR_KEY);
		ANIMATED_BLOCK = register("animated_block", EntityType.Builder.of(AnimatedBlock::new, MobCategory.MISC).fireImmune().sized(1F, 1.25F).clientTrackingRange(4).updateInterval(10), ANIMATED_BLOCK_KEY);
		ANTLION = register("antlion", EntityType.Builder.of(Antlion::new, MobCategory.MONSTER).sized(1.9F, 0.9F).fireImmune(), ANTLION_KEY);
		ANTLION_BOSS = register("antlion_boss", EntityType.Builder.of(AntlionBoss::new, MobCategory.MONSTER).sized(6.0F, 2.0F).fireImmune(), ANTLION_BOSS_KEY);
		ANTLION_MINI_BOSS = register("antlion_mini_boss", EntityType.Builder.of(AntlionMiniBoss::new, MobCategory.MONSTER).sized(2.75F, 1.2F).fireImmune(), ANTLION_MINI_BOSS_KEY);
		BABY_SOLIFUGE = register("baby_solifuge", EntityType.Builder.of(BabySolifuge::new, MobCategory.MONSTER).sized(1.0F, 0.5F).fireImmune(), BABY_SOLIFUGE_KEY);
		BABY_TARANTULA = register("baby_tarantula", EntityType.Builder.of(BabyTarantula::new, MobCategory.MONSTER).sized(0.75F, 0.25F), BABY_TARANTULA_KEY);
		BED_BUG = register("bed_bug", EntityType.Builder.of(BedBug::new, MobCategory.MONSTER).sized(0.75F, 0.6F), BED_BUG_KEY);
		BEETLE = register("beetle", EntityType.Builder.of(Beetle::new, MobCategory.CREATURE).sized(1.6F, 0.9F), BEETLE_KEY);
		BEETLE_LARVA = register("beetle_larva", EntityType.Builder.of(BeetleLarva::new, MobCategory.CREATURE).sized(0.9F, 0.5F), BEETLE_LARVA_KEY);
		BLACK_ANT = register("black_ant", EntityType.Builder.of(BlackAnt::new, MobCategory.CREATURE).sized(0.9F, 0.4F), BLACK_ANT_KEY);
		BLACK_WIDOW = register("black_widow", EntityType.Builder.of(BlackWidow::new, MobCategory.MONSTER).sized(0.7F, 0.325F).fireImmune(), BLACK_WIDOW_KEY);
		BOG_MAW = register("bog_maw", EntityType.Builder.of(BogMaw::new, MobCategory.MONSTER).sized(1.0F, 0.8F).fireImmune(), BOG_MAW_KEY);
		BOMBARDIER_BEETLE = register("bombardier_beetle", EntityType.Builder.of(BombardierBeetle::new, MobCategory.MONSTER).sized(1.9F, 0.9F), BOMBARDIER_BEETLE_KEY);
		BOMBARDIER_BEETLE_LARVA = register("bombardier_beetle_larva", EntityType.Builder.of(BombardierBeetleLarva::new, MobCategory.MONSTER).sized(0.9F, 0.5F), BOMBARDIER_BEETLE_LARVA_KEY);
		BOT_FLY = register("bot_fly", EntityType.Builder.of(BotFly::new, MobCategory.MONSTER).sized(0.9F, 0.75F), BOT_FLY_KEY);
		BOT_FLY_LARVA = register("bot_fly_larva", EntityType.Builder.of(BotFlyLarva::new, MobCategory.MONSTER).sized(0.5F, 0.2F).fireImmune(), BOT_FLY_LARVA_KEY);
		CENTIPEDE = register("centipede", EntityType.Builder.of(Centipede::new, MobCategory.MONSTER).sized(0.3125F, 0.3125F), CENTIPEDE_KEY);
		CHAMELEON_TICK = register("chameleon_tick", EntityType.Builder.of(ChameleonTick::new, MobCategory.MONSTER).sized(1.0F, 1.0F), CHAMELEON_TICK_KEY);
		CICADA = register("cicada", EntityType.Builder.of(Cicada::new, MobCategory.CREATURE).sized(1.0F, 0.4F), CICADA_KEY);
		CROP_WEEVIL = register("crop_weevil", EntityType.Builder.of(CropWeevil::new, MobCategory.CREATURE).sized(1F, 0.5F), CROP_WEEVIL_KEY);
		CRUSHROOM = register("crushroom", EntityType.Builder.of(Crushroom::new, MobCategory.MONSTER).sized(2.5F, 3F), CRUSHROOM_KEY);
		DRAGON_FLY = register("dragon_fly", EntityType.Builder.of(Dragonfly::new, MobCategory.MONSTER).sized(2.5F, 1.0F).fireImmune(), DRAGON_FLY_KEY);
		FIRE_ANT = register("fire_ant", EntityType.Builder.of(FireAnt::new, MobCategory.MONSTER).sized(0.75F, 0.25F), FIRE_ANT_KEY);
		FIRE_ANT_SOLDIER = register("fire_ant_soldier", EntityType.Builder.of(FireAntSoldier::new, MobCategory.MONSTER).sized(0.9F, 0.5F), FIRE_ANT_SOLDIER_KEY);
		FLY = register("fly", EntityType.Builder.of(Fly::new, MobCategory.MONSTER).sized(0.5F, 0.45F), FLY_KEY);
		FUNGAL_WEEVIL = register("fungal_weevil", EntityType.Builder.of(FungalWeevil::new, MobCategory.CREATURE).sized(1F, 0.5F), FUNGAL_WEEVIL_KEY);
		GOO_BALL = register("goo_ball", EntityType.Builder.<GooBall>of(GooBall::new, MobCategory.MISC).fireImmune().sized(0.5F, 0.5F), GOO_BALL_KEY);
		GLOW_WORM = register("glow_worm", EntityType.Builder.of(GlowWorm::new, MobCategory.CREATURE).sized(1.5F, 0.5F), GLOW_WORM_KEY);
		GRASSHOPPER = register("grasshopper", EntityType.Builder.of(Grasshopper::new, MobCategory.CREATURE).sized(1.3F, 0.75F), GRASSHOPPER_KEY);
		HONEY_POT_ANT = register("honey_pot_ant", EntityType.Builder.of(HoneyPotAnt::new, MobCategory.CREATURE).sized(0.9F, 0.4F), HONEY_POT_ANT_KEY);
		JUMPING_SPIDER = register("jumping_spider", EntityType.Builder.of(JumpingSpider::new, MobCategory.CREATURE).sized(0.7F, 0.5F), JUMPING_SPIDER_KEY);
		LAVA_WEB_SPIDER = register("lava_web_spider", EntityType.Builder.of(LavaWebSpider::new, MobCategory.MONSTER).sized(3F, 1.5F).fireImmune(), LAVA_WEB_SPIDER_KEY);
		LOCUST = register("locust", EntityType.Builder.of(Locust::new, MobCategory.MONSTER).sized(2F, 1F), LOCUST_KEY);
		MAGMA_CRAWLER = register("magma_crawler", EntityType.Builder.of(MagmaCrawler::new, MobCategory.MONSTER).sized(0.9F, 0.9F), MAGMA_CRAWLER_KEY);
		MIDGE_SWARM = register("midge_swarm", EntityType.Builder.of(MidgeSwarm::new, MobCategory.MONSTER).sized(0.9F, 0.9F), MIDGE_SWARM_KEY);
		MONEY_SPIDER = register("money_spider", EntityType.Builder.of(MoneySpider::new, MobCategory.MONSTER).sized(0.6F, 0.4F).fireImmune(), MONEY_SPIDER_KEY);
		MOSQUITO = register("mosquito", EntityType.Builder.of(Mosquito::new, MobCategory.MONSTER).sized(0.9F, 1.3F), MOSQUITO_KEY);
		MOTH = register("moth", EntityType.Builder.of(Moth::new, MobCategory.MONSTER).sized(1.8F, 0.5F), MOTH_KEY);
		POND_SKATER = register("pond_skater", EntityType.Builder.of(PondSkater::new, MobCategory.CREATURE).sized(1.0F, 1.0F), POND_SKATER_KEY);
		PRAYING_MANTIS = register("praying_mantis", EntityType.Builder.of(PrayingMantis::new, MobCategory.CREATURE).sized(2.0F, 2.5F).fireImmune(), PRAYING_MANTIS_KEY);
		PUNCHROOM = register("punchroom", EntityType.Builder.of(Punchroom::new, MobCategory.MONSTER).sized(1F, 1F).fireImmune(), PUNCHROOM_KEY);
		RHINO_BEETLE = register("rhino_beetle", EntityType.Builder.of(RhinoBeetle::new, MobCategory.CREATURE).sized(2.3F, 1.4F), RHINO_BEETLE_KEY);
		SCORPION = register("scorpion", EntityType.Builder.of(Scorpion::new, MobCategory.MONSTER).sized(2.0F, 2.0F).fireImmune(), SCORPION_KEY);
		SCYTODES = register("scytodes", EntityType.Builder.of(Scytodes::new, MobCategory.MONSTER).sized(2F, 1F).fireImmune(), SCYTODES_KEY);
		SOLIFUGE = register("solifuge", EntityType.Builder.of(Solifuge::new, MobCategory.MONSTER).sized(2.5F, 1.25F), SOLIFUGE_KEY);
		STAG_BEETLE = register("stag_beetle", EntityType.Builder.of(StagBeetle::new, MobCategory.CREATURE).sized(2.5F, 1.2F), STAG_BEETLE_KEY);
		TARANTULA = register("tarantula", EntityType.Builder.of(Tarantula::new, MobCategory.MONSTER).sized(1.3F, 0.6F), TARANTULA_KEY);
		TARANTULA_MINI_BOSS = register("tarantula_mini_boss", EntityType.Builder.of((EntityType<TarantulaMiniBoss> type, Level level) -> new TarantulaMiniBoss(level), MobCategory.MONSTER).sized(4.0F, 1.2F), TARANTULA_MINI_BOSS_KEY);
		THROWN_BLOCK_AS_ITEM = register("thrown_block_as_item", EntityType.Builder.<ThrownBlockAsItem>of(ThrownBlockAsItem::new, MobCategory.MISC).fireImmune().sized(0.5F, 0.5F), THROWN_BLOCK_AS_ITEM_KEY);
		TITAN_BEETLE = register("titan_beetle", EntityType.Builder.of(TitanBeetle::new, MobCategory.CREATURE).sized(2.5F, 1.2F), TITAN_BEETLE_KEY);
		UMBER_GOLEM = register("umber_golem", EntityType.Builder.of(UmberGolem::new, MobCategory.MONSTER).sized(1.0F, 1.0F).fireImmune(), UMBER_GOLEM_KEY);
		VELVET_WORM = register("velvet_worm", EntityType.Builder.of(VelvetWorm::new, MobCategory.MONSTER).sized(0.3125F, 0.3125F), VELVET_WORM_KEY);
		WASP = register("wasp", EntityType.Builder.of(Wasp::new, MobCategory.MONSTER).sized(0.5F, 0.4F), WASP_KEY);
		WOODLOUSE = register("woodlouse", EntityType.Builder.of(Woodlouse::new, MobCategory.CREATURE).sized(1.0F, 0.3F), WOODLOUSE_KEY);
		WORKER_BEE = register("worker_bee", EntityType.Builder.of(WorkerBee::new, MobCategory.CREATURE).sized(0.5F, 0.5F), WORKER_BEE_KEY);
		ZOMBIE_ANT = register("zombie_ant", EntityType.Builder.of(ZombieAnt::new, MobCategory.MONSTER).sized(1.5F, 0.75F), ZOMBIE_ANT_KEY);
		ZOMBIE_ANT_SOLDIER = register("zombie_ant_soldier", EntityType.Builder.of(ZombieAntSoldier::new, MobCategory.MONSTER).sized(1.75F, 0.75F), ZOMBIE_ANT_SOLDIER_KEY);
	}

	private static <T extends Entity> DeferredHolder<EntityType<?>, EntityType<T>> register(String name, EntityType.Builder<T> builder, ResourceKey<EntityType<?>> key) {
		return ENTITY_TYPES.register(name, () -> builder.build(key));
	}

	private static ResourceKey<EntityType<?>> createKey(String name) {
		return ResourceKey.create(Registries.ENTITY_TYPE, Erebus.prefix(name));
	}
}
