package erebus.datagen;

import net.minecraft.client.data.models.model.ModelTemplate;
import net.minecraft.client.data.models.model.ModelTemplates;
import net.minecraft.client.data.models.model.TextureSlot;
import net.minecraft.core.Direction;
import net.minecraft.resources.Identifier;

public class ModModelTemplates {

    public static TextureSlot STEM = TextureSlot.create("Stem");
    public static TextureSlot PETAL = TextureSlot.create("Petal");
    public static TextureSlot PETAL_CHASE = TextureSlot.create("PetalChase");
    public static TextureSlot STIGMA = TextureSlot.create("Stigma");

    public enum FlowerType {
        NORMAL,
        THICK,
        DROOP
    }

    public static ModelTemplate honeyTreatBite(int bite) {
        int[] bites = new int[]{1, 3, 5, 7, 9, 11, 13};
        return ModelTemplates
                .create(TextureSlot.PARTICLE, TextureSlot.TOP, TextureSlot.BOTTOM, TextureSlot.SIDE, TextureSlot.INSIDE)
                .extend()
                .parent(Identifier.fromNamespaceAndPath("minecraft", "block/block"))
                .element(elements -> elements
                        .from(bites[bite], 0, 1)
                        .to(15, 8, 15)
                        .allFaces((direction, builder) -> {
                            switch (direction) {
                                case DOWN -> builder.texture(TextureSlot.BOTTOM).cullface(Direction.DOWN);
                                case UP -> builder.texture(TextureSlot.TOP);
                                case NORTH, SOUTH, EAST -> builder.texture(TextureSlot.SIDE);
                                case WEST -> builder.texture(TextureSlot.INSIDE);
                            }
                        })
                ).build();
    }

    public static ModelTemplate dustLayer(int height) {
        return ModelTemplates
                .create(TextureSlot.PARTICLE, TextureSlot.TEXTURE)
                .extend()
                .parent(Identifier.fromNamespaceAndPath("minecraft", "block/block"))
                .element(elements -> elements
                        .from(0, 0, 0)
                        .to(16, height, 16)
                        .allFaces((direction, builder) -> {
                            switch (direction) {
                                case DOWN -> builder.texture(TextureSlot.TEXTURE).uvs(0, 0, 16, 16).cullface(Direction.DOWN);
                                case UP -> builder.texture(TextureSlot.TEXTURE).uvs(0, 0, 16, 16);
                                case NORTH -> builder.texture(TextureSlot.TEXTURE).uvs(0, 16 - height, 16, 16).cullface(Direction.NORTH);
                                case SOUTH -> builder.texture(TextureSlot.TEXTURE).uvs(0, 16 - height, 16, 16).cullface(Direction.SOUTH);
                                case EAST -> builder.texture(TextureSlot.TEXTURE).uvs(0, 16 - height, 16, 16).cullface(Direction.EAST);
                                case WEST -> builder.texture(TextureSlot.TEXTURE).uvs(0, 16 - height, 16, 16).cullface(Direction.WEST);
                            }
                        })
                ).build();
    }

    public static ModelTemplate hollowLog() {
        return ModelTemplates
                .create(TextureSlot.PARTICLE, TextureSlot.TOP, TextureSlot.END, TextureSlot.SIDE)
                .extend()
                .parent(Identifier.fromNamespaceAndPath("minecraft", "block/block"))
                .element((elements) -> elements
                        .from(1, 0, 0)
                        .to(15, 1, 16)
                        .allFaces((direction, builder) -> {
                            switch (direction) {
                                case NORTH -> builder.texture(TextureSlot.TOP).uvs(0, 15, 14, 16).cullface(Direction.NORTH);
                                case SOUTH -> builder.texture(TextureSlot.TOP).uvs(0, 15, 14, 16).cullface(Direction.SOUTH);
                                case UP, DOWN -> builder.texture(TextureSlot.TOP).uvs(0, 0, 14, 16);
                                case EAST, WEST -> builder.texture(TextureSlot.END).uvs(0, 15, 16, 16);
                            }
                        })
                )
                .element((elements) -> elements
                        .from(1, 15, 0)
                        .to(15, 16, 16)
                        .allFaces((direction, builder) -> {
                            switch (direction) {
                                case NORTH -> builder.texture(TextureSlot.TOP).uvs(0, 0, 14, 1).cullface(Direction.NORTH);
                                case SOUTH -> builder.texture(TextureSlot.TOP).uvs(0, 0, 14, 1).cullface(Direction.SOUTH);
                                case UP, DOWN -> builder.texture(TextureSlot.TOP).uvs(0, 0, 14, 16);
                                case EAST, WEST -> builder.texture(TextureSlot.END).uvs(0, 0, 16, 1);
                            }
                        })
                )
                .element((elements) -> elements
                        .from(0, 1, 0)
                        .to(1, 15, 16)
                        .allFaces((direction, builder) -> {
                            switch (direction) {
                                case NORTH -> builder.texture(TextureSlot.END).uvs(15, 1, 16, 15).cullface(Direction.NORTH);
                                case SOUTH -> builder.texture(TextureSlot.END).uvs(0, 1, 1, 15).cullface(Direction.SOUTH);
                                case EAST, WEST -> builder.texture(TextureSlot.SIDE).uvs(0, 1, 16, 15);
                                case UP, DOWN -> builder.texture(TextureSlot.TOP).uvs(0, 0, 1, 16);
                            }
                        })
                )
                .element((elements) -> elements
                        .from(15, 1, 0)
                        .to(16, 15, 16)
                        .allFaces((direction, builder) -> {
                            switch (direction) {
                                case NORTH -> builder.texture(TextureSlot.END).uvs(0, 1, 1, 15).cullface(Direction.NORTH);
                                case SOUTH -> builder.texture(TextureSlot.END).uvs(15, 1, 16, 15).cullface(Direction.SOUTH);
                                case EAST, WEST -> builder.texture(TextureSlot.SIDE).uvs(0, 1, 16, 15);
                                case UP, DOWN -> builder.texture(TextureSlot.TOP).uvs(0, 0, 1, 16);
                            }
                        })
                )
                .element((elements) -> elements
                        .from(1, 1, 0)
                        .to(15, 15, 0)
                        .face(Direction.NORTH, (builder) -> builder.texture(TextureSlot.END).uvs(1, 1, 15, 15).cullface(Direction.NORTH))
                        .face(Direction.SOUTH, (builder) -> builder.texture(TextureSlot.END).uvs(1, 1, 15, 15).cullface(Direction.SOUTH))
                )
                .element((elements) -> elements
                        .from(1, 1, 16)
                        .to(15, 15, 16)
                        .face(Direction.NORTH, (builder) -> builder.texture(TextureSlot.END).uvs(1, 1, 15, 15).cullface(Direction.NORTH))
                        .face(Direction.SOUTH, (builder) -> builder.texture(TextureSlot.END).uvs(1, 1, 15, 15).cullface(Direction.SOUTH))
                )
                .build();
    }

    public static ModelTemplate flower() {
        return ModelTemplates
                .create(TextureSlot.PARTICLE, STEM, PETAL, STIGMA)
                .extend()
                .parent(Identifier.fromNamespaceAndPath("minecraft", "block/cube_all"))
                .element((elements) -> elements
                        .from(7.0F, 0.0F, 7.0F)
                        .to(8.0F, 6.0F, 8.0F)
                        .face(Direction.NORTH, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 12.0F))
                        .face(Direction.EAST, (builder) -> builder.texture(STEM).uvs(2.0F, 0.0F, 4.0F, 12.0F))
                        .face(Direction.SOUTH, (builder) -> builder.texture(STEM).uvs(4.0F, 0.0F, 6.0F, 12.0F))
                        .face(Direction.WEST, (builder) -> builder.texture(STEM).uvs(6.0F, 0.0F, 8.0F, 12.0F))
                        .face(Direction.DOWN, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                )
                .element((elements) -> elements
                        .from(7.0F, 1.0F, 6.0F)
                        .to(8.0F, 2.0F, 7.0F)
                        .face(Direction.NORTH, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.EAST, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.WEST, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.UP, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.DOWN, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                )
                .element((elements) -> elements
                        .from(7.0F, 0.0F, 5.0F)
                        .to(8.0F, 1.0F, 6.0F)
                        .face(Direction.NORTH, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.EAST, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.SOUTH, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.WEST, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.UP, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.DOWN, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                )
                .element((elements) -> elements
                        .from(7.0F, 1.0F, 8.0F)
                        .to(8.0F, 2.0F, 9.0F)
                        .face(Direction.EAST, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.SOUTH, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.WEST, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.UP, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.DOWN, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                )
                .element((elements) -> elements
                        .from(7.0F, 0.0F, 9.0F)
                        .to(8.0F, 1.0F, 10.0F)
                        .face(Direction.NORTH, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.EAST, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.SOUTH, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.WEST, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.UP, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.DOWN, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                )
                .element((elements) -> elements
                        .from(8.0F, 1.0F, 7.0F)
                        .to(9.0F, 2.0F, 8.0F)
                        .face(Direction.NORTH, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.EAST, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.SOUTH, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.UP, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.DOWN, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                )
                .element((elements) -> elements
                        .from(9.0F, 0.0F, 7.0F)
                        .to(10.0F, 1.0F, 8.0F)
                        .face(Direction.NORTH, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.EAST, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.SOUTH, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.WEST, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.UP, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.DOWN, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                )
                .element((elements) -> elements
                        .from(6.0F, 1.0F, 7.0F)
                        .to(7.0F, 2.0F, 8.0F)
                        .face(Direction.NORTH, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.SOUTH, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.WEST, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.UP, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.DOWN, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                )
                .element((elements) -> elements
                        .from(5.0F, 0.0F, 7.0F)
                        .to(6.0F, 1.0F, 8.0F)
                        .face(Direction.NORTH, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.EAST, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.SOUTH, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.WEST, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.UP, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.DOWN, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                )
                .element((elements) -> elements
                        .from(7.0F, 5.0F, 6.0F)
                        .to(8.0F, 6.0F, 7.0F)
                        .face(Direction.NORTH, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.EAST, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.WEST, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.DOWN, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                )
                .element((elements) -> elements
                        .from(7.0F, 5.0F, 8.0F)
                        .to(8.0F, 6.0F, 9.0F)
                        .face(Direction.EAST, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.SOUTH, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.WEST, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.DOWN, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                )
                .element((elements) -> elements
                        .from(8.0F, 5.0F, 7.0F)
                        .to(9.0F, 6.0F, 8.0F)
                        .face(Direction.NORTH, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.EAST, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.SOUTH, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.DOWN, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                )
                .element((elements) -> elements
                        .from(6.0F, 5.0F, 7.0F)
                        .to(7.0F, 6.0F, 8.0F)
                        .face(Direction.NORTH, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.SOUTH, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.WEST, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.DOWN, (builder) -> builder.texture(STEM).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                )
                .element((elements) -> elements
                        .from(6.0F, 6.0F, 6.0F)
                        .to(9.0F, 7.0F, 9.0F)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 6.0F, 2.0F))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 6.0F, 2.0F))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 6.0F, 2.0F))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 6.0F, 2.0F))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 6.0F, 6.0F))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 6.0F, 6.0F))
                )
                .element((elements) -> elements
                        .from(7.0F, 7.0F, 7.0F)
                        .to(8.0F, 8.0F, 8.0F)
                        .face(Direction.NORTH, (builder) -> builder.texture(STIGMA).uvs(7.0F, 4.0F, 9.0F, 6.0F))
                        .face(Direction.EAST, (builder) -> builder.texture(STIGMA).uvs(7.0F, 4.0F, 9.0F, 6.0F))
                        .face(Direction.SOUTH, (builder) -> builder.texture(STIGMA).uvs(7.0F, 4.0F, 9.0F, 6.0F))
                        .face(Direction.WEST, (builder) -> builder.texture(STIGMA).uvs(7.0F, 4.0F, 9.0F, 6.0F))
                        .face(Direction.UP, (builder) -> builder.texture(STIGMA).uvs(7.0F, 4.0F, 9.0F, 6.0F))
                )
                .element((elements) -> elements
                        .from(5.0F, 6.0F, 5.0F)
                        .to(6.0F, 7.0F, 6.0F)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                )
                .element((elements) -> elements
                        .from(9.0F, 6.0F, 5.0F)
                        .to(10.0F, 7.0F, 6.0F)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                )
                .element((elements) -> elements
                        .from(4.0F, 6.0F, 7.0F)
                        .to(6.0F, 7.0F, 8.0F)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(8.0F, 4.0F, 4.0F, 2.0F))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(6.0F, 4.0F, 2.0F, 2.0F))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(8.0F, 4.0F, 4.0F, 2.0F))
                )
                .element((elements) -> elements
                        .from(9.0F, 6.0F, 7.0F)
                        .to(11.0F, 7.0F, 8.0F)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0.0F, 4.0F, 4.0F, 2.0F))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(8.0F, 4.0F, 4.0F, 2.0F))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, -3.0F, 4.0F))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(8.0F, 4.0F, 4.0F, 2.0F))
                )
                .element((elements) -> elements
                        .from(5.0F, 6.0F, 9.0F)
                        .to(6.0F, 7.0F, 10.0F)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                )
                .element((elements) -> elements
                        .from(9.0F, 6.0F, 9.0F)
                        .to(10.0F, 7.0F, 10.0F)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                )
                .element((elements) -> elements
                        .from(7.0F, 6.0F, 4.0F)
                        .to(8.0F, 7.0F, 6.0F)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 4.0F, 2.0F))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 4.0F, 2.0F))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 4.0F))
                )
                .element((elements) -> elements
                        .from(7.0F, 6.0F, 9.0F)
                        .to(8.0F, 7.0F, 11.0F)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 4.0F, 2.0F))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 4.0F, 2.0F))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0.0F, 8.0F, 2.0F, 4.0F))
                )
                .element((elements) -> elements
                        .from(4.0F, 5.0F, 10.0F)
                        .to(5.0F, 6.0F, 11.0F)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                )
                .element((elements) -> elements
                        .from(10.0F, 5.0F, 10.0F)
                        .to(11.0F, 6.0F, 11.0F)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                )
                .element((elements) -> elements
                        .from(10.0F, 5.0F, 4.0F)
                        .to(11.0F, 6.0F, 5.0F)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                )
                .element((elements) -> elements
                        .from(4.0F, 5.0F, 4.0F)
                        .to(5.0F, 6.0F, 5.0F)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                )
                .element((elements) -> elements
                        .from(7.0F, 5.0F, 11.0F)
                        .to(8.0F, 6.0F, 12.0F)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                )
                .element((elements) -> elements
                        .from(7.0F, 5.0F, 3.0F)
                        .to(8.0F, 6.0F, 4.0F)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                )
                .element((elements) -> elements
                        .from(11.0F, 5.0F, 7.0F)
                        .to(12.0F, 6.0F, 8.0F)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                )
                .element((elements) -> elements
                        .from(3.0F, 5.0F, 7.0F)
                        .to(4.0F, 6.0F, 8.0F)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL).uvs(0.0F, 0.0F, 2.0F, 2.0F))
                )
                .build();
    }

    public static ModelTemplate flowerThick() {
        return ModelTemplates
                .create(TextureSlot.PARTICLE, STEM, PETAL, PETAL_CHASE, STIGMA)
                .extend()
                .parent(Identifier.fromNamespaceAndPath("minecraft", "block/cube_all"))
                .element((elements) -> elements
                        .from(7, 0, 7)
                        .to(8, 6, 8)
                        .face(Direction.NORTH, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 12))
                        .face(Direction.EAST, (builder) -> builder.texture(STEM).uvs(2, 0, 4, 12))
                        .face(Direction.SOUTH, (builder) -> builder.texture(STEM).uvs(4, 0, 6, 12))
                        .face(Direction.WEST, (builder) -> builder.texture(STEM).uvs(6, 0, 8, 12))
                        .face(Direction.DOWN, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(7, 1, 6)
                        .to(8, 2, 7)
                        .face(Direction.NORTH, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(7, 0, 5)
                        .to(8, 1, 6)
                        .face(Direction.NORTH, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(7, 1, 8)
                        .to(8, 2, 9)
                        .face(Direction.EAST, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(7, 0, 9)
                        .to(8, 1, 10)
                        .face(Direction.NORTH, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(8, 1, 7)
                        .to(9, 2, 8)
                        .face(Direction.NORTH, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(9, 0, 7)
                        .to(10, 1, 8)
                        .face(Direction.NORTH, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(6, 1, 7)
                        .to(7, 2, 8)
                        .face(Direction.NORTH, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(5, 0, 7)
                        .to(6, 1, 8)
                        .face(Direction.NORTH, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(7, 5, 6)
                        .to(8, 6, 7)
                        .face(Direction.NORTH, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(7, 6, 5)
                        .to(8, 7, 6)
                        .face(Direction.NORTH, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(7, 5, 8)
                        .to(8, 6, 9)
                        .face(Direction.EAST, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(7, 6, 9)
                        .to(8, 7, 10)
                        .face(Direction.EAST, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(8, 5, 7)
                        .to(9, 6, 8)
                        .face(Direction.NORTH, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(9, 6, 7)
                        .to(10, 7, 8)
                        .face(Direction.NORTH, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(6, 5, 7)
                        .to(7, 6, 8)
                        .face(Direction.NORTH, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(5, 6, 7)
                        .to(6, 7, 8)
                        .face(Direction.NORTH, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(6, 6, 6)
                        .to(9, 7, 9)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 6, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 6, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 6, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 6, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 6, 6))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 6, 6))
                )
                .element((elements) -> elements
                        .from(9, 7, 6)
                        .to(10, 8, 9)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0, 0, 6, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0, 0, 6, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 6))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 6))
                )
                .element((elements) -> elements
                        .from(5, 7, 6)
                        .to(6, 8, 9)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0, 0, 6, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0, 0, 6, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 6))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 6))
                )
                .element((elements) -> elements
                        .from(6, 7, 5)
                        .to(9, 8, 6)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 6, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0, 0, 6, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL).uvs(0, 0, 6, 2))
                )
                .element((elements) -> elements
                        .from(6, 7, 9)
                        .to(9, 8, 10)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 6, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0, 0, 6, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL).uvs(0, 0, 6, 2))
                )
                .element((elements) -> elements
                        .from(7, 8, 7)
                        .to(8, 9, 8)
                        .face(Direction.NORTH, (builder) -> builder.texture(STIGMA).uvs(7, 4, 9, 6))
                        .face(Direction.EAST, (builder) -> builder.texture(STIGMA).uvs(7, 4, 9, 6))
                        .face(Direction.SOUTH, (builder) -> builder.texture(STIGMA).uvs(7, 4, 9, 6))
                        .face(Direction.WEST, (builder) -> builder.texture(STIGMA).uvs(7, 4, 9, 6))
                        .face(Direction.UP, (builder) -> builder.texture(STIGMA).uvs(7, 4, 9, 6))
                )
                .element((elements) -> elements
                        .from(7, 7, 6)
                        .to(8, 8, 9)
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0, 0, 6, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0, 0, 6, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 6))
                )
                .element((elements) -> elements
                        .from(6, 7, 7)
                        .to(9, 8, 8)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 6, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 6, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0, 0, 6, 2))
                )
                .element((elements) -> elements
                        .from(6, 8, 4)
                        .to(9, 9, 5)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 6, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0, 0, 6, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL).uvs(0, 0, 6, 2))
                )
                .element((elements) -> elements
                        .from(6, 8, 10)
                        .to(9, 9, 11)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 6, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0, 0, 6, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL).uvs(0, 0, 6, 2))
                )
                .element((elements) -> elements
                        .from(4, 8, 6)
                        .to(5, 9, 9)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0, 0, 6, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0, 0, 6, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 6))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 6))
                )
                .element((elements) -> elements
                        .from(10, 8, 6)
                        .to(11, 9, 9)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0, 0, 6, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0, 0, 6, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 6))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 6))
                )
                .element((elements) -> elements
                        .from(5, 8, 5)
                        .to(6, 9, 6)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(9, 8, 5)
                        .to(10, 9, 6)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(5, 8, 7)
                        .to(6, 9, 8)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(9, 8, 7)
                        .to(10, 9, 8)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(5, 8, 9)
                        .to(6, 9, 10)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(9, 8, 9)
                        .to(10, 9, 10)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(7, 8, 5)
                        .to(8, 9, 6)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(7, 8, 9)
                        .to(8, 9, 10)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(6, 9, 4)
                        .to(7, 10, 5)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(8, 9, 4)
                        .to(9, 10, 5)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(6, 9, 10)
                        .to(7, 10, 11)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(8, 9, 10)
                        .to(9, 10, 11)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(10, 9, 6)
                        .to(11, 10, 7)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(10, 9, 8)
                        .to(11, 10, 9)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(4, 9, 6)
                        .to(5, 10, 7)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(4, 9, 8)
                        .to(5, 10, 9)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL_CHASE).uvs(0, 0, 2, 2))
                )
                .build();
    }

    public static ModelTemplate flowerTall() {
        return ModelTemplates
                .create(TextureSlot.PARTICLE, STEM, PETAL, PETAL_CHASE, STIGMA)
                .extend()
                .parent(Identifier.fromNamespaceAndPath("minecraft", "block/cube_all"))
                .element((elements) -> elements
                        .from(7, 0, 7)
                        .to(8, 8, 8)
                        .face(Direction.NORTH, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 12))
                        .face(Direction.EAST, (builder) -> builder.texture(STEM).uvs(2, 0, 4, 12))
                        .face(Direction.SOUTH, (builder) -> builder.texture(STEM).uvs(4, 0, 6, 12))
                        .face(Direction.WEST, (builder) -> builder.texture(STEM).uvs(6, 0, 8, 12))
                        .face(Direction.DOWN, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(7, 1, 6)
                        .to(8, 2, 7)
                        .face(Direction.NORTH, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(7, 0, 5)
                        .to(8, 1, 6)
                        .face(Direction.NORTH, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(7, 1, 8)
                        .to(8, 2, 9)
                        .face(Direction.EAST, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(7, 0, 9)
                        .to(8, 1, 10)
                        .face(Direction.NORTH, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(8, 1, 7)
                        .to(9, 2, 8)
                        .face(Direction.NORTH, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(9, 0, 7)
                        .to(10, 1, 8)
                        .face(Direction.NORTH, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(6, 1, 7)
                        .to(7, 2, 8)
                        .face(Direction.NORTH, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(5, 0, 7)
                        .to(6, 1, 8)
                        .face(Direction.NORTH, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(STEM).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(7, 8, 7)
                        .to(8, 9, 8)
                        .face(Direction.NORTH, (builder) -> builder.texture(STIGMA).uvs(7, 4, 9, 6))
                        .face(Direction.EAST, (builder) -> builder.texture(STIGMA).uvs(7, 4, 9, 6))
                        .face(Direction.SOUTH, (builder) -> builder.texture(STIGMA).uvs(7, 4, 9, 6))
                        .face(Direction.WEST, (builder) -> builder.texture(STIGMA).uvs(7, 4, 9, 6))
                        .face(Direction.UP, (builder) -> builder.texture(STIGMA).uvs(7, 4, 9, 6))
                        .face(Direction.DOWN, (builder) -> builder.texture(STIGMA).uvs(7, 4, 9, 6))
                )
                .element((elements) -> elements
                        .from(7, 7, 8)
                        .to(8, 8, 9)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(7, 7, 6)
                        .to(8, 8, 7)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(6, 7, 7)
                        .to(7, 8, 8)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(8, 7, 7)
                        .to(9, 8, 8)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(7, 8, 5)
                        .to(8, 9, 6)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(6, 8, 6)
                        .to(7, 9, 7)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(8, 8, 6)
                        .to(9, 9, 7)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(9, 8, 7)
                        .to(10, 9, 8)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(8, 8, 8)
                        .to(9, 9, 9)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(7, 8, 9)
                        .to(8, 9, 10)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(6, 8, 8)
                        .to(7, 9, 9)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(5, 8, 7)
                        .to(6, 9, 8)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(7, 9, 4)
                        .to(8, 10, 5)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(9, 9, 5)
                        .to(10, 10, 6)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(10, 9, 7)
                        .to(11, 10, 8)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(4, 9, 7)
                        .to(5, 10, 8)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(7, 9, 10)
                        .to(8, 10, 11)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(9, 9, 9)
                        .to(10, 10, 10)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(5, 9, 9)
                        .to(6, 10, 10)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                )
                .element((elements) -> elements
                        .from(5, 9, 5)
                        .to(6, 10, 6)
                        .face(Direction.NORTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.EAST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.SOUTH, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.WEST, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.UP, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                        .face(Direction.DOWN, (builder) -> builder.texture(PETAL).uvs(0, 0, 2, 2))
                )
                .build();
    }
}